config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.save
    redirect_to @car
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to @car
  end

  def destroy
    Car.find(params[:id]).destroy
    redirect_to cars_path
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :engine, :year, :tyre_type, :tyre_manufacturer, :engine_config, :wins, :drivers_championship, :constructors_championship, :image, :weight)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<section>
  <h1>Edit car info</h1>
  <div class="show">
    <%= form_with(model: @car) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :car_name %>
      </div>

      <div class="field">
        <%= form.label :engine %>
        <%= form.text_field :engine, id: :car_engine %>
      </div>

      <div class="field">
        <%= form.label :year %>
        <%= form.number_field :year, id: :car_year %>
      </div>

      <div class="field">
        <%= form.label :tyre_type %>
        <%= form.text_field :type_type, id: :car_tyre_type %>
      </div>

      <div class="field">
        <%= form.label :tyre_manufacturer %>
        <%= form.text_field :tyre_manufacturer, id: :car_tyre_manufacturer %>
      </div>

      <div class="field">
        <%= form.label :engine_config %>
        <%= form.text_field :engine_config, id: :car_engine %>
      </div>

      <div class="field">
        <%= form.label :weight %>
        <%= form.number_field :weight, id: :car_weight %>
      </div>

      <div class="field">
        <%= form.label :wins %>
        <%= form.number_field :wins, id: :car_wins %>
      </div>

      <div class="field">
        <%= form.label :drivers_championship %>
        <%= form.text_field :drivers_championship, id: :car_drivers_championship %>
      </div>

      <div class="field">
        <%= form.label :constructors_championship %>
      <%= form.text_field :constructors_championship, id: :car_constructors_championship %>
      </div>

      <div class="field">
        <%= form.label :image %>
        <%= form.text_field :image, id: :car_image %>
      </div>
      
      <div class="submit">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</section>

app/views/cars/index.html.erb
<h1>Formula 1 Car Collection</h1>

<div class="row">
  <% @cars.each do |car| %>
    <div class="col-md-3" onclick="window.location = '/cars/<%= car.id %>'">
      <p class="title"><%= link_to car.name, car %> - <%= car.year %></p>
      <img src="<%= car.image %>" class = "img-responsive">
    </div>
  <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<section>
  <h1>Add a new car</h1>
  <div class="show">
    <%= form_with(model: @car) do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :car_name %>
      </div>

      <div class="field">
        <%= form.label :engine %>
        <%= form.text_field :engine, id: :car_engine %>
      </div>

      <div class="field">
        <%= form.label :year %>
        <%= form.number_field :year, id: :car_year %>
      </div>

      <div class="field">
        <%= form.label :tyre_type %>
        <%= form.text_field :type_type, id: :car_tyre_type %>
      </div>

      <div class="field">
        <%= form.label :tyre_manufacturer %>
        <%= form.text_field :tyre_manufacturer, id: :car_tyre_manufacturer %>
      </div>

      <div class="field">
        <%= form.label :engine_config %>
        <%= form.text_field :engine_config, id: :car_engine %>
      </div>

      <div class="field">
        <%= form.label :weight %>
        <%= form.number_field :weight, id: :car_weight %>
      </div>

      <div class="field">
        <%= form.label :wins %>
        <%= form.number_field :wins, id: :car_wins %>
      </div>

      <div class="field">
        <%= form.label :drivers_championship %>
        <%= form.text_field :drivers_championship, id: :car_drivers_championship %>
      </div>

      <div class="field">
        <%= form.label :constructors_championship %>
      <%= form.text_field :constructors_championship, id: :car_constructors_championship %>
      </div>

      <div class="field">
        <%= form.label :image %>
        <%= form.text_field :image, id: :car_image %>
      </div>

      <div class="submit">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</section>

app/views/cars/show.html.erb
<section>
  <div class="show">
    <h1><%= @car.name %> - <%= @car.year %></h1>

    <img src="<%= @car.image %>" class = "img-responsive">

    <p>Engine: <%= @car.engine %> <%= @car.engine_config %></p>

    <p>Tyres: <%= @car.tyre_manufacturer %>, <%= @car.tyre_type %></p>

    <p>Weight: <%= @car.weight %>kg</p>

    <p>Race wins: <%= @car.wins %></p>

    <p>Won drivers championship: <%= @car.drivers_championship %></p>

    <p>Won constructers championship: <%= @car.constructors_championship %></p>

    <p id="edit-delete"><%= link_to 'Edit', edit_car_path(@car) %> | <%= link_to 'Delete', @car, method: :delete %></p>
      
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormulaOne</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body">
    <div id="main-container" class="container">
    <nav>
      <a href="/cars">Home</a>
      <a href="/cars/new">Add a Car</a>
    </nav>
            
      <%= yield %>   

    </div>
  </body>
</html>